stages:
- build
- release

build:
  image: rust:1.44.1-alpine
  stage: build
  script:
    - apk add --no-cache musl-dev
    - rustup default nightly
    - cargo build --release
  artifacts:
    paths:
      - target/release/jellydesktop
