stages:
- build
- release

build:
  image: rust:1.42
  stage: build
  script:
    - apt-get update
    - apt-get install openssl openssl-dev musl-tools -y
    - rustup default nightly && rustup update
    - rustup target add x86_64-unknown-linux-musl --toolchain=nightly
    - cargo build --release --target=x86_64-unknown-linux-musl
