[package]
name = "jellydesktop"
version = "0.1.0"
authors = ["D3fus <d3fus@ejected.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.8"
termion = "1.5"

